!define UI_COLOR #1D8900

!define PARSER_COLOR #ADD8E6

!define COMMAND_COLOR #F8C8DC

!define STORAGE_COLOR #A38300

!define TRANSACTION_COLOR #83E769

!define EXPENSE_COLOR #C8C8FA

!define MAIN_COLOR #83E769

!define USER_COLOR #000000
!define USER_COLOR_T1 #E97451